# Generated by Django 4.0.3 on 2022-06-11 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioAlumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Nombre de Usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electronico')),
                ('nombres', models.CharField(max_length=250, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=250, verbose_name='Apellidos')),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_administrador', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreArea', models.CharField(max_length=100, unique=True, verbose_name='Area')),
                ('informacion', models.TextField(max_length=5000, verbose_name='Informacion')),
            ],
        ),
        migrations.CreateModel(
            name='ejemplos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True, verbose_name='Titulo')),
                ('contenido', models.TextField(max_length=5000, verbose_name='Contenido')),
            ],
        ),
        migrations.CreateModel(
            name='Estadisticas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('porcentaje', models.FloatField()),
                ('IdAlumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.areas')),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='repPreguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField(max_length=5000, verbose_name='Preguntas')),
                ('IdArea', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.areas')),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='temas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temaNombre', models.CharField(max_length=100, unique=True, verbose_name='Tema')),
                ('informacion', models.TextField(max_length=5000, verbose_name='Informacion')),
                ('videolink', models.URLField(verbose_name='Link')),
                ('imagen', models.FileField(upload_to='', verbose_name='Imagen')),
                ('IdArea', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.areas')),
            ],
        ),
        migrations.CreateModel(
            name='respuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=1000, verbose_name='Respuestas')),
                ('correcta', models.BooleanField(default=False)),
                ('preguntas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.reppreguntas')),
            ],
        ),
        migrations.CreateModel(
            name='estadisticasPreguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdEstadistica', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.estadisticas')),
                ('IdPregunta', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.reppreguntas')),
            ],
        ),
        migrations.AddField(
            model_name='usuarioalumnos',
            name='IDGrado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.grado'),
        ),
        migrations.AddField(
            model_name='usuarioalumnos',
            name='IDSeccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.seccion'),
        ),
    ]
