# Generated by Django 3.2.7 on 2022-04-20 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=50)),
                ('IDarea', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.tema')),
            ],
        ),
        migrations.CreateModel(
            name='pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=50)),
                ('IDrespuesta', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.respuesta')),
                ('IDtema', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.tema')),
            ],
        ),
    ]
