# Generated by Django 4.0.3 on 2022-06-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_temas_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadisticas',
            name='fecha',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha'),
        ),
    ]
