# Generated by Django 3.2.7 on 2022-04-20 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_pregunta_respuesta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuesta',
            old_name='IDarea',
            new_name='IDtema',
        ),
    ]
