# Generated by Django 3.2.7 on 2022-06-11 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_temas_imagen'),
        ('home', '0003_rename_idarea_respuesta_idtema'),
    ]

    operations = [
    ]
